on: [push]
name: Rebuild Website

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@master
      
      - run: pip install -r requirements.txt
          
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
    
      - name: Clear build directory
        run: |
          find build/* | xargs rm -rf;
          
      - name: Setup Build Directory
        run: |
          mkdir -p ./build/de ./build/en

      - name: Build
        run: python3 build.py --language de
        
      - name: Redirect english files
        run: |
          ls build/en | xargs -I {} sh -c "./redirect.py /en/{} > ./build/{}"
          
      - name: Bundle
        run: |
          tar --dereference --hard-dereference --directory build -cvf ./artifact.tar --exclude=.git --exclude=.github .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
          retention-days: "1"
          if-no-files-found: error
          
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

